[project]
name = 'nft-bridge'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []

[contracts.hello-stacks]
path = 'contracts/hello-stacks.clar'
clarity_version = 2
epoch = 2.1
[contracts.stx-bridge]
path = 'contracts/stx-bridge.clar'
clarity_version = 2
epoch = 2.1
[contracts.crash-testnet]
path = 'contracts/crash-testnet.clar'
clarity_version = 2
epoch = 2.1
depends_on = ["nft-trait","operable","commission-trait"]

[contracts.operable]
path = 'contracts/operable.clar'
clarity_version = 2
epoch = 2.1

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.nft-ownable-trait]
path = 'contracts/nft-ownable-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.commission-trait]
path = 'contracts/commission-trait.clar'
clarity_version = 2
epoch = 2.1


[contracts.arkadiko-oracle-v1]
path = 'contracts/arkadiko-oracle-v1.clar'
clarity_version = 2
epoch = 2.1
depends_on = ["oracle-trait"]
[contracts.oracle-trait]
path = 'contracts/oracle-trait.clar'
clarity_version = 2
epoch = 2.1




[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
